### ISSUE TITLE
SALTS automatically unsubscribes TV shows

### ISSUE THREAD

**Issue by JordanLongstaff** [tknorris/salts#101]
Every time I watch a single episode of a TV show in my Subscriptions list, after I have finished watching the episode, SALTS automatically removes that show from the list. This happens when I access the episode from the Kodi library or my "TV Show Collection". I see no reason why it should be doing this, but I do know I shouldn't have to keep re-subscribing after every episode.

**Comment by tknorris** [comment]
You are using your watchlist as your subscription list, and the trakt design is to remove shows from your watchlist when you've watched a single episode of them. That's just how it works. The solution is to not use your watchlist as your subscription list.

**Comment by JordanLongstaff** [comment]
OK, well, I'm not sure how to fix that. Is there something in Settings that I need to change?
