### ISSUE TITLE
Cannot play any movies

### ISSUE THREAD

**Issue by JordanLongstaff** [tknorris/salts#102]
Every time I try to play a movie from the library, the following error message appears in Kodi's log:

23:11:44 T:4536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Error: mode |get_sources| requested argument |trakt_id| but it was not provided.
                                            Traceback (most recent call last):
                                              File "C:\Users\LONGSTAFF\AppData\Roaming\Kodi\addons\plugin.video.salts\default.py", line 2152, in <module>
                                                sys.exit(main())
                                              File "C:\Users\LONGSTAFF\AppData\Roaming\Kodi\addons\plugin.video.salts\default.py", line 2146, in main
                                                url_dispatcher.dispatch(mode, queries)
                                              File "C:\Users\LONGSTAFF\AppData\Roaming\Kodi\addons\plugin.video.salts\salts_lib\url_dispatcher.py", line 67, in dispatch
                                                raise Exception(message)
                                            Exception: Error: mode |get_sources| requested argument |trakt_id| but it was not provided.
                                            -->End of Python script error report<--

**Comment by tknorris** [comment]
I need a full log, Post it to xbmclogs.com and link to it here.

**Comment by JordanLongstaff** [comment]
OK. Here it is: http://xbmclogs.com/pkaersmhj
You'll find the error message somewhere after 23:30:00.

**Comment by tknorris** [comment]
Looks like this strm file was added with a much older version of SALTS. Since then the format of the SALTS strm files have changed. If you either re-add them to your library or, if they are in a subscription list, run a subscription update and it should resolve itself.
