### ISSUE TITLE
Automatically download subtitle

### ISSUE THREAD

**Issue by abhinavkssk** [tknorris/salts#104]
Is it possible to have an option to automatically download the top subtitle in the list, instead of having to select from a list when the auto download subtitle option is enabled? ( Having to select from a list also doesn't make a lot of sense as it's not really possible know beforehand which subtitle would be in sync with the stream anyway )

**Comment by tknorris** [comment]
Choosing subtitles isn't really about sync, it's that different choices have different function like Hearing Impaired vs corrected vs HD. I prefer to allow the user to select rather than auto-select.

**Comment by abhinavkssk** [comment]
Maybe have an additional option so that people who would prefer to use it can do so? This would be helpful for instance when auto-playing episodes in Library so that you wouldn’t constantly be interrupted by pop-ups.

**Comment by tknorris** [comment]
I'll think about it...

**Comment by abhinavkssk** [comment]
Created a PR which adds this option #105
