### ISSUE TITLE
Content with special characters adding as "_" and thus not scanning

### ISSUE THREAD

**Issue by jt196** [tknorris/salts#108]
So on performing an "add to library" to the folder in userdata, for example "Marvel's Jessica Jones" is added as "Marvel_s Jessica Jones" and not being recognised by the TV scraper. Consider some rules ie apostrophe replaced by nothing, "&" replaced by "and" etc.

**Comment by tknorris** [comment]
It works that way for a reason. You should read the [FAQ](https://github.com/tknorris/salts/wiki/Frequently-Asked-Questions#when-using-library-integration-what-do-i-do-when-the-show-or-movie-is-scraped-into-kodi-incorrectly)
