### ISSUE TITLE
Getting some add to library issues

### ISSUE THREAD

**Issue by jt196** [tknorris/salts#109]
Must have crashed 50 times when scraping info from programs added to the system. Mac OSX. Kodi Isen 15.2

This is the log message I'm getting:

20:55:21 T:123145304526848  NOTICE: Thread BackgroundLoader start, auto delete: false
20:55:21 T:123145305063424  NOTICE: Thread LanguageInvoker start, auto delete: false
20:55:21 T:123145305063424  NOTICE: -->Python Interpreter Initialized<--
20:55:21 T:123145305063424  NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting GUI proc (6.0.15)
20:55:23 T:123145304526848  NOTICE: Thread BackgroundLoader start, auto delete: false
20:55:23 T:123145305600000  NOTICE: Thread JobWorker start, auto delete: true
20:55:32 T:123145302839296  NOTICE: Thread VideoInfoDownloader start, auto delete: false

**Comment by tknorris** [comment]
Those log lines have nothing to do with SALTS.
