### ISSUE TITLE
library management

### ISSUE THREAD

**Issue by yepmouidriss** [tknorris/salts#110]
it is very uncofortable that the tv shows do not update by them self even after i check and configure and configure again and again, the library items do not change SALTS does not add new episodes to te tv shows you placed in the library like Genesis even when I chosed every hour, at start up, still nothing. can you try to fix that please . thank you for your work, courage.

**Comment by tknorris** [comment]
Make sure you follow ALL of the instructions here: https://github.com/tknorris/salts/wiki/Frequently-Asked-Questions#how-do-i-add-shows-and-movies-to-the-kodi-library-from-salts

If the problem persists, open a new issue and include a link to your kodi log that includes running a subscription update.

**Comment by yepmouidriss** [comment]
thank you
it is a little bit complicate but it works now
thank you
