### ISSUE TITLE
My Next Episodes 

### ISSUE THREAD

**Issue by carlcarpenter248** [tknorris/salts#112]
Hey man. Thanks for all your contributions. I'm experiencing a crash when playing shows from "My Next Episodes." Im using Kodi 15.2 on a Windows 10 machine. I'm trakt integrated. Just a heads up, if you want a log let me know. This crash happens after a show completes on its own. Doesn't happen when I stop manually. I get a Windows notification that "Kodi has stopped responding"

**Comment by tknorris** [comment]
I need a log.

**Comment by tknorris** [comment]
no response, closing
