### ISSUE TITLE
Export movie title to the search subtitle addon.

### ISSUE THREAD

**Issue by mac1202** [tknorris/salts#113]
Hi I would like to watch movie with subtitle but the subtitle addon failed to find any subtitle because salts export the movie url instead of the movie title. 
![Screenshot](http://i.imgur.com/Qds6AYO.png)
If it's doable can you export the movie title instead of the url, Thank you.

**Comment by tknorris** [comment]
I'm already setting the metadata correctly. It looks like that addon is pulling the search from the filename which I can't change.
