### ISSUE TITLE
TV subscription error

### ISSUE THREAD

**Issue by marszalek1** [tknorris/salts#114]
Somebody know why in salts addon when i opening TV subscription list, its not opening. I've got error addon message, but when I open Movies subscription list everything is OK. Yesterday everything was ok. Pls help.

Log: http://pastebin.com/0NdYwQQA

**Comment by tknorris** [comment]
You have the default sort order for your sub list set to "Title" on trakt. It appears that either one of the items is missing a title or there's a bug in that part of the code. Switch it back to "rank" for now on trakt and it should fix it.

**Comment by tknorris** [comment]
It would help if you turn on debug and the browse into "My Subscriptions" and upload that log so I can track down where the problem is.

**Comment by marszalek1** [comment]
that was very fast, and this fix my problem. Thank You

**Comment by marszalek1** [comment]
Her is log with debug on: http://xbmclogs.com/prkmztm7r
after I change listiong on trakt

**Comment by tknorris** [comment]
Can you change it back to title to generate the log? I need that to find the problem.

**Comment by marszalek1** [comment]
ok one moment

**Comment by marszalek1** [comment]
done: http://xbmclogs.com/p1wxg1yod

**Comment by tknorris** [comment]
Thanks I'll check it out when I'm back at a computer.

**Comment by tknorris** [comment]
So, I'll have a fix in the next build, but the problem is you added a season of "Degrassi: Next Class" to your subscription list and then sorted by title, but season's don't have titles. If you remove the season for now, then the title sort will work until I get a fix out.

**Comment by marszalek1** [comment]
I done like You wrote and it's OK. One more time thanks for fast solutions.
