### ISSUE TITLE
support for subtitles in Hebrew

### ISSUE THREAD

**Issue by itzikg** [tknorris/salts#117]
Hi hello Is it possible to add support for subtitles in Hebrew Language?

**Comment by tknorris** [comment]
I can only support the subtitles that addic7ed supports. IF they support hebrew then you can use them in the SALTS. You can always use one of the subtitles addons.

**Comment by itzikg** [comment]
You can not do in your addon as lambda made him?

**Comment by tknorris** [comment]
No, I'm just not interested in doing so. They don't serve any purpose for me.

**Comment by itzikg** [comment]
Too bad
