### ISSUE TITLE
New categories?

### ISSUE THREAD

**Issue by xsmashx88x** [tknorris/salts#121]
Sorry, I don't know where else to send or post this but 

Norris any chance you can add like Movie Genre like horror and that, and by year like 2014,2015,2016..

not sure if you have been asked this before but love this add-on and would make me and proly everyone else who does use this add-on happy to have them options. Thank you for you hard work and keep to it SALTS is fucking beast

**Comment by tknorris** [comment]
It's been asked many times. The trakt API doesn't provide that type of filtering/search so SALTS doesn't either.

**Comment by xsmashx88x** [comment]
oh okay, sorry had no clue just would make searching for shows and movies better, thanks for the comment back :)
