### ISSUE TITLE
Option to skip season views

### ISSUE THREAD

**Issue by icegothic** [tknorris/salts#122]
It would be nice to be able to go from TvShow view to episode view directly (skipping the season view); implying that the episodes of all seasons would be merged in the episode view.

**Comment by tknorris** [comment]
Can you explain why you need/want this?

**Comment by icegothic** [comment]
Sure. :-)

In the past, I've been using the "Genesis" addon (which has this kind of option) until I discovered SALTs. Navigating between views was instantaneous so I got used to the fast episodes access.

Caching seems to be handled differently with SALTs; reloading data every time we change view makes it longer to navigate between them.

Personnaly, I like seeing all episodes of a show in the same place; no need to go back and forth between seasons and episodes views to find a specific episode.

This ain't a bug but that'd just be nice :-)

**Comment by tknorris** [comment]
So, I took a look at this and it would require quite a few code changes and increase complexity in several places. I just don't think it's worth the effort. Sorry.
