### ISSUE TITLE
Hebrew on trakt!

### ISSUE THREAD

**Issue by lidormalicb** [tknorris/salts#123]
Dear Friend ,
Create great Addon KODI and that is salts.
There is a Hebrew, is a little poor and her missing words.
Not that I'm sending you a message, I am sending you this message in Hebrew Because the Trakt does not have where information on the film is in English, you can add a scraper with a film or series name in Hebrew?
Thank you
Lidor Malich

**Comment by tknorris** [comment]
SALTS only matches in English because that's all trakt has and that's the most frequent matches.

**Comment by lidormalicb** [comment]
And you can not add a filter to show the information in Hebrew?
This he take me to the wall of movies, because through my galaxy Can I
Lhosic and remove things easily.

or

If you can link me off or an explanation of how to make your own filter and
thus help the Israeli community of plugin (is greatly increased Shop is 50K
people)
I ask your help

2016-01-26 18:53 GMT+02:00 tknorris <notifications@github.com>:

> SALTS only matches in English because that's all trakt has and that's the
> most frequent matches.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tknorris/salts/issues/123#issuecomment-175112552>.
>



-- 

שהיה לנו יום נהדר.

*לידור מליח <lidormalich@gmail.com>,*

*דוא"ל*: lidormalich@gmail.com

lidormalich.wordpress.com

**Comment by lidormalicb** [comment]
And you can not add a filter to show the information in Hebrew?
This he take me to the wall of movies, because through my galaxy, I can add and remove things easily.

or

If you can link me off or an explanation of how to make your own filter and thus help the Israeli community of plugin (is greatly increased Shop is 50K people)
I ask your help

**Comment by tknorris** [comment]
Sorry, it's just not something I'm interested in. I have no interest in converting people to use SALTS. If it's useful, use it, If it's not, don't.
