### ISSUE TITLE
Autoplay (Next)

### ISSUE THREAD

**Issue by kaleem619** [tknorris/salts#125]
Auto-play works beautifully when skipping through broken links.

But I regularly find Auto-Play still tries to play a link which either can't buffer, ends up being porn or is in another language.
I want to be able to tell the auto-play to try and auto-play the next best link
OR
To somehow tell the auto-play which set of links to start autoplaying from in 'Select Source'

This would be a very serious addition that would help so much, could this please be seriously considered ?

**Comment by tknorris** [comment]
Sorry, I don't use autoplay so I'm not interested in enhancing it beyond how it works now.
