### ISSUE TITLE
Shows being removed from lists

### ISSUE THREAD

**Issue by PAULAAJ2601** [tknorris/salts#126]
Hi, using the beta version 1.0.107 and having a couple of issues.  First one is that since updating to the 1.0.107 my shows are no longer sorting alphabetically.  Will sometimes still do it temporarily but then within secs goes back to the other view. Obviously this is not a major issue and i can live with it but it just make thing easier when looking for a specific show.   Secondly I am having an issue with shows being removed from my custom list.  Had the same problem with the other versions of SALTS (not beta) which is why i changed to using the beta version.  It is a list I have created myself on TRAKT and added to SALTS as my subscription list.  I contacted TRAKT and they are sure its not an issue their end and advised me to contact you.  I originally thought it was a problem with shows that have ended but it also keeps removing a current TV show (The Cleveland Show).  It also seems to be the same shows over and over again and then suddenly another show starts disappearing.  Many thanks

**Comment by tknorris** [comment]
SALTS sorts lists in the same order they are on trakt and respects your default sort order you set for each list. If you want it alphabetized in SALTS, then set title as the default sort on trakt.

As far as shows being removed from a list, I'll bet anything that you are using the watchlist as your subscription list even though you say your are not. Post a link to your log of opening My Subscriptions. https://www.tvaddons.ag/posting-error-logs-kodi/

**Comment by PAULAAJ2601** [comment]
Not sure how to post a link to log but within SALTS i went into the MY LISTS section, highlighted my list and used the menu to set it as my subscription list

**Comment by tknorris** [comment]
Do you have hide watched turned on? To check slide out the side menu and see if "Hide Watched" is turned on. When you check on trakt, is that show still on the list?

**Comment by PAULAAJ2601** [comment]
"Hide watched" is not turned on as have many shows on the list that are still showing even though all episodes have been viewed.  The aforementioned shows also do not show up on the list when viewing via TRAKT once they have disappeared from SALTS.  Also with regards to sorting alphabetically, shows are sorted alphabetically when viewing my list on TRAKT

**Comment by tknorris** [comment]
Here is how to upload your log. https://www.tvaddons.ag/posting-error-logs-kodi/ Follow that, and then paste the link you are sent here. Note that SALTS doesn't remove anything from any list unless you do so yourself, so I suspect something else is going on here.

Also, paste a link to your user profile on trakt, I want to look at the list that you say is not sorted.

**Comment by PAULAAJ2601** [comment]
Here is the link to my trakt profile:-
https://trakt.tv/users/paulaaj2601

Part of the procedure for posting the log is to recreate the error but can't actually do this myself.  The shows are still there at the moment as I re-added them earlier, its just something that will happen itself sometime within the next day or so.  What do you want me to do with regards to log, still post one?

**Comment by tknorris** [comment]
> Part of the procedure for posting the log is to recreate the error but can't actually do this myself. The shows are still there at the moment as I re-added them earlier, its just something that will happen itself sometime within the next day or so. What do you want me to do with regards to log, still post one?

Do two things: 1) Navigate into My Subscriptions and 2) Run a manual sub update
There is literally no code in SALTS that removes shows from lists w/o user initiation, so I'm guessing something else is going on.

**Comment by PAULAAJ2601** [comment]
have done that, now what?

**Comment by tknorris** [comment]
Post a link to the log that you uploaded.

**Comment by PAULAAJ2601** [comment]
http://xbmclogs.com/p7dhvsvii

BTW your help is very much appreciated

**Comment by tknorris** [comment]
Which shows have disappeared from your subscription?

**Comment by PAULAAJ2601** [comment]
They're still there at the moment but the ones that disappeared before include:-
iCarly
Jekyll & Hyde
Victorious
Mighty Med
Sam & Cat
The Cleveland Show
there have been other but can't remember them

**Comment by PAULAAJ2601** [comment]
Don't know if its relevant but i am using a droidplayer running kodi 14.8

**Comment by tknorris** [comment]
You have prune ended shows (in the Library Integration) turned on I bet. All the shows that you say are disappearing are ended shows.

**Comment by tknorris** [comment]
Also, I still need you to follow me back on trakt so I can see your lists

**Comment by PAULAAJ2601** [comment]
Just checked settings and Prune Ended Shows in Library Integration is not selected.  How do I follow you on trakt?

**Comment by PAULAAJ2601** [comment]
Think I'm now following you on trakt

**Comment by tknorris** [comment]
Do you only have one machine w/ subscriptions or more than one?

**Comment by PAULAAJ2601** [comment]
I have 2.  One upstairs and one down both linked to the same trakt account

**Comment by tknorris** [comment]
Did you check the one upstairs to see if it has Prune ended shows on? I really think that's the problem.

**Comment by PAULAAJ2601** [comment]
just checked and again its unchecked

**Comment by PAULAAJ2601** [comment]
could there be something overriding the settings?  I also had include watchlist in MNE unchecked but anything I watch be it in my list or not comes up in Next Episodes?

**Comment by tknorris** [comment]
That settings forces SALTS to include shows that you haven't watched but are on your watchlist in MNE, so no, it's not related.

**Comment by tknorris** [comment]
FYI, I found the bug on list sorting. It's triggered when the cached version of the list is accessed rather than pulled directly from Trakt.

**Comment by PAULAAJ2601** [comment]
is that something I can sort my end?

**Comment by tknorris** [comment]
> is that something I can sort my end?

No

**Comment by PAULAAJ2601** [comment]
Is it something I've caused or is it a bug in the last update?

**Comment by tknorris** [comment]
> Is it something I've caused or is it a bug in the last update?

It's a bug in the last update. List Caching is new in 1.0.107

**Comment by PAULAAJ2601** [comment]
Ok.  At least I now now I haven't buggered it up, lol.  Do you think the other problem may be sorted by a fresh install of the addon?

**Comment by tknorris** [comment]
I haven't yet found why the shows are being deleted. Lets do this on that issue. Lets leave this open, and in a few days if shows disappear again, post a new log. Hopefully that will shed some light on what's causing it. If it's not Prune Ended shows, then I don't see anything else it can be.

**Comment by PAULAAJ2601** [comment]
Just to confuse things a bit more, I have another show 'Big Time Rush' that used to disappear when using the non beta version of SALTS that has stayed in my list, even though it is another 'ENDED SHOW''.   

The disappearance of 'The Cleveland Show' is baffling me.  All the other shows I mentioned previously, Icarly, Mighty Med etc are all shows that have ended, were marked as all episodes watched but had not actually been viewed on this setup of kodi.  The Cleveland Show is one that is watched almost daily, not all the episodes have been marked as watched and not all episodes have been viewed

**Comment by tknorris** [comment]
The fact that they are all ended shows tells me that some way, some how one of your machine's has Prune Ended shows turned on. There are only three ways that a show gets removed from a list
1. It's the watchlist and you watch an episode of that show
2. You manually remove it.
3. You run a sub update and have Prune Ended shows turned on.

The only one of those that consistently removes ended shows is #3

**Comment by PAULAAJ2601** [comment]
I can totally understand what your saying, but I can assure you that it is showing as unchecked on both boxes. Also as I said BIG TIME RUSH is an ended show and that has remained in my list when the others have been removed. Will be updating to JARVIS soon so droidplayer informs me, so will do a fresh install of SALTS then and see if that sorts anything

**Comment by tknorris** [comment]
FYI, Build 1.0.108 should fix your sorting issue.

**Comment by tknorris** [comment]
Any more instances of this happening? If not I'll close the issue and you can open a new one if it happens again.

**Comment by PAULAAJ2601** [comment]
No, all seems fine at the moment.  Thanks for all your help
