### ISSUE TITLE
movietv.to episode problems

### ISSUE THREAD

**Issue by grant2258** [tknorris/salts#127]
Hi I'm using salts 1.08 it's only doing this with some tv shows. I'm watching bones season 4 if I pick any episode from it plays the one above it. Ie when I pick 4x16 it will play 4x17

**Comment by tknorris** [comment]
Did you check movietv to see if it's off by one as well?

**Comment by grant2258** [comment]
Will check now

**Comment by tknorris** [comment]
If so (and I quick glance tells me it probably is), then you can use SRU to correct it manually: https://github.com/tknorris/salts/wiki/Frequently-Asked-Questions#how-do-i-correct-the-addon-when-it-has-picked-the-wrong-sources-for-a-tv-show-movie-or-episode

**Comment by grant2258** [comment]
Your right it's the website itself sorry about that cheers for the link
