### ISSUE TITLE
FileFactory Link Won't Play - No Error Shows

### ISSUE THREAD

**Issue by kaleem619** [tknorris/salts#128]
Filefactory link starts by saying 'Working' making me think it will play, but then suddenly decides not to without any errors popping up (SOMETIMES a message says error sent to log file)
Does this on most if not all Filefactory links

I've copied what went into the log file, is it a problem with Filefactory or my Kodi/SALTS 

20:20:20 T:2601487168  NOTICE: Previous line repeats 1 times.
20:20:20 T:2601487168  NOTICE: Thread LanguageInvoker start, auto delete: false
20:20:20 T:3032705856  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
20:20:20 T:2601487168  NOTICE: -->Python Interpreter Initialized<--
20:20:21 T:2601487168  NOTICE: Stream All The Sources: Version: |1.0.108| Queries: |{'rand': '1454098221.7', 'class_url': 'http://www.filefactory.com/stream/3e6i9rali8u7', 'episode': '18', 'class_name': 'alluc.com', 'season': '26', 'direct': 'False', 'video_type': 'Episode', 'trakt_id': '455', 'mode': 'resolve_source'}|
20:20:21 T:2601487168  NOTICE: Stream All The Sources: Args: |['plugin://plugin.video.salts/', '37', '?rand=1454098221.7&trakt_id=455&class_url=http%3A%2F%2Fwww.filefactory.com%2Fstream%2F3e6i9rali8u7&episode=18&mode=resolve_source&class_name=alluc.com&season=26&direct=False&video_type=Episode']|
20:20:21 T:2601487168  NOTICE: Stream All The Sources: Calling |resolve_source| for mode |resolve_source| with pos args |['resolve_source', 'http://www.filefactory.com/stream/3e6i9rali8u7', False, 'Episode', '455', 'alluc.com']| and kwargs |{'season': '26', 'episode': '18'}|
20:20:21 T:2601487168  NOTICE: Stream All The Sources: Warning: Arguments |{'rand': '1454098221.7'}| were passed but unused by |resolve_source| for mode |resolve_source|
20:20:21 T:2601487168  NOTICE: URLResolver: Initializing URLResolver version: 2.10.10
20:20:21 T:2601487168  NOTICE: URLResolver: No Settings Update Needed
20:20:23 T:2601487168  NOTICE: Stream All The Sources: Indirect hoster_url not supported by urlresolver: http://www.filefactory.com/stream/3e6i9rali8u7
20:20:24 T:3032909632  NOTICE: DVDPlayer: Opening: http://www.filefactory.com/stream/3e6i9rali8u7
20:20:24 T:3032909632 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
20:20:24 T:2576309056  NOTICE: Thread DVDPlayer start, auto delete: false
20:20:24 T:2576309056  NOTICE: Creating InputStream
20:20:24 T:2576309056  NOTICE: Creating Demuxer
20:20:24 T:2601487168  NOTICE: Thread FileCache start, auto delete: false
20:20:24 T:2576309056   ERROR: Open - error probing input format, http://www.filefactory.com/stream/3e6i9rali8u7
20:20:24 T:2576309056   ERROR: OpenDemuxStream - Error creating demuxer
20:20:24 T:2576309056  NOTICE: CDVDPlayer::OnExit()
20:20:24 T:3032909632   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.salts/?rand=1454098221.7&trakt_id=455&class_url=http%3A%2F%2Fwww.filefactory.com%2Fstream%2F3e6i9rali8u7&episode=18&mode=resolve_source&class_name=alluc.com&season=26&direct=False&video_type=Episode]
20:20:24 T:3032909632  NOTICE: CDVDPlayer::CloseFile()
20:20:24 T:3032909632  NOTICE: DVDPlayer: waiting for threads to exit
20:20:24 T:3032909632  NOTICE: DVDPlayer: finished waiting
20:20:24 T:3032909632  NOTICE: CDVDPlayer::CloseFile()
20:20:24 T:3032909632  NOTICE: DVDPlayer: waiting for threads to exit
20:20:24 T:3032909632  NOTICE: DVDPlayer: finished waiting
20:20:25 T:2818333504  NOTICE: Stream All The Sources: Service: Playback Stopped
20:20:25 T:2576309056  NOTICE: Thread JobWorker start, auto delete: true
20:21:27 T:2576309056  NOTICE: Thread BackgroundLoader start, auto delete: false
20:21:27 T:2601487168  NOTICE: Thread JobWorker start, auto delete: true

**Comment by tknorris** [comment]
you need a debrid account for file factory to work

**Comment by kaleem619** [comment]
I have got a Real Debrid account tknorris ???

**Comment by tknorris** [comment]
From your log, you don't have the RD account enabled.

**Comment by kaleem619** [comment]
That's strange ! I've got the green links, and most of them work - I authorized my account with Kodi and it hasn't given me problems or notifications otherwise ...

Is there anything you can advise me to do to get past the issue ??

**Comment by kaleem619** [comment]
I have just checked my URLResolver - RD is definitely enabled, although it's priority is 90, which is what a few guides told me to set it to otherwise it wouldn't work

Don't know if that helps ?

**Comment by tknorris** [comment]
The problem is the url for the stream doesn't match RD's validation for File Factory. They except "/file/" in the url, the one you have has "/stream/" in it

**Comment by kaleem619** [comment]
Okay, is there anything I can do to correct the issue ?

**Comment by tknorris** [comment]
You can report the problem to RD. Tell them that their  /hosts/regex API call is not supporting that form of file factory url. http://www.filefactory.com/stream/3e6i9rali8u7

You can also point them to this github issue.

**Comment by kaleem619** [comment]
Thank you - I've reported the problem to RD

**Comment by kaleem619** [comment]
Solved - RD replied back and fixed the problem. FileFactory should now be sorted for anyone else having the same issue

**Comment by tknorris** [comment]
Glad to hear it.
