### ISSUE TITLE
Dizimag

### ISSUE THREAD

**Issue by ananias47** [tknorris/salts#131]
Hi again dizimag doesnt seem to work i have no sourced any longer is this because the capatca of the site?? 

Thnx

**Comment by tknorris** [comment]
Yes.

**Comment by NitroXenon** [comment]
But I can use browser to visit Dizimag without typing captcha. Any idea why?? Dizimag is a great HD source :cry:

**Comment by tknorris** [comment]
I can not, I think it's geo based...

**Comment by NitroXenon** [comment]
I tried specto today and it could get sources from Dizimag. Any idea why??

**Comment by ananias47** [comment]
Nitro i used specto and i didnt get any dizimag what did u search and you see source thnx

**Comment by NitroXenon** [comment]
Homeland Season 5 Episode 1
