### ISSUE TITLE
Sources Sorting

### ISSUE THREAD

**Issue by ffsi** [tknorris/salts#132]
On forum, there is a list of the aggregator sites that are in HD, it would be interesting an option to enable the search only in HD sources. (or a button that turns off all that are not)

**Comment by tknorris** [comment]
There isn't a definitive list of scrapers that only have HD. The lists you've seen are just individual's experience, but things change all the time. SALTS is designed to classify the link, not the scraper. One week, a scraper may return lots of HD, next week none or vice versa. In other words, what you are suggesting won't really work.
