### ISSUE TITLE
Movietv

### ISSUE THREAD

**Issue by ananias47** [tknorris/salts#133]
Hi my friend why you remove this scrapper it works well on same tv shows when others dont

Thnx

**Comment by tknorris** [comment]
It no longer works.

**Comment by NitroXenon** [comment]
Yeah after the "end" query was removed, the server returned 410 Gone error. If I set the "end" query to 999, which is the max value, I can play the video for about 16 mins.

**Comment by tknorris** [comment]
I'll check it, but 16 mins is no better than 5. The shortest shows are 21 minutes

**Comment by NitroXenon** [comment]
Yeah that's no doubt.
