### ISSUE TITLE
Dizilab sezonlukdizi dayt. Se

### ISSUE THREAD

**Issue by ananias47** [tknorris/salts#134]
I have no sources anymore although the sites are working and doesnt have protection

Thnx

P. S.  Is there somewere else u want to post the issues??

**Comment by tknorris** [comment]
You can open a thread on our forum but actually I have automated testers for all the scrapers so I'd rather you not report scraper problems at all. There are so many others just pick a source from another one.

**Comment by ananias47** [comment]
Yes but this is the best for hd all the others eather not playing or it is very lagy please fix it when u can 

Thnx
Where is the forum??

**Comment by tknorris** [comment]
forums.tvaddons.ag/

**Comment by ananias47** [comment]
My friend the problem a think is on the openelec because when i try it on my android or pc it shows the source i did a fresh install on my openelec on rpi on the first search it shows me all the scrapers but the no source again. The problem has shown today the oast 20 days it works well

**Comment by tknorris** [comment]
Someone else said that too. If you have a log of it working the first time and not the 2nd time, that might help.
