### ISSUE TITLE
Freezing when trying to play from Liberary

### ISSUE THREAD

**Issue by Hanney72** [tknorris/salts#135]
Hi tknorris

Firstly, many thanks for such a great addon that has truly filled the void left by the departing Genesis.

I have been encountering in the last few updates (now running latest beta version) a total freeze of SALTS and my Nexus Player when trying to play a TV episode or movie from my SALTS library on the home page! I usually have to reboot the entire box.

I can however play directly from addon, or strangely from my library when having "autoplay sources" enabled! For some reason it seems to freeze when trying to display the available sources in my library once the the filter has been applied.

Is this something that you are aware of or is it something known to you that can be rectified through my settings?

FYI:

1. Running Jarvis RC3 (however issue persisted with different versions of Kodi)
2. Running Android M (6.0.1)
3. Do not experience issues with other addons with library integration capabilities.

Please let me know if you have any questions and many thanks for your support in advance.

Regards
Hanney

**Comment by tknorris** [comment]
Did you turn off custom dialogs from the library in addon settings?

**Comment by Hanney72** [comment]
Wow, that was quick! It's on, should I disable and try?

**Comment by tknorris** [comment]
yes, that setting being turned on causes crashes on some systems..that's why it's off by default...So, either you installed some idiots build that didn't know any better or you turned it on unknowingly.

**Comment by Hanney72** [comment]
Actually I turned it on purpose, as I thought it was responsible for showing the sources as they are being scrapped! Correct me if I am wrong!

**Comment by Hanney72** [comment]
Just tried it now and it worked - You have made our day mate!!! Thanks a million!

The amount of updates to your addon is testimony to how hard you work! Fantastic stuff!

p.s: I never used a build, always do my own and look after the updates, too much fun to miss out on otherwise! :)

**Comment by tknorris** [comment]
Yep, it does show the progress as sources are scraped, but the reason it's off by default is because it triggers a bug in kodi on some systems that causes a hang. There's no way to predict which ones it will cause the bug on so you just have to try, and turn it off if it causes the freeze. Glad you got it sorted.
