### ISSUE TITLE
Auto mark as watched for items in library 

### ISSUE THREAD

**Issue by IdanRadai** [tknorris/salts#136]
Hi
first of all - great app! keep the good work!

I've linked my Kodi library as your wiki says (works great) with my trait.tv account.
for some reason after I'm finishing a movie/episode that movie/episode isn't marked as watched 
Is there a way to set it to mark those item as watched automatically ?

**Comment by tknorris** [comment]
https://github.com/tknorris/salts/wiki/Frequently-Asked-Questions#why-isnt-my-kodi-andor-trakttv-watched-status-updated-automatically
