### ISSUE TITLE
Dizilab hardcoded subtitles

### ISSUE THREAD

**Issue by NitroXenon** [tknorris/salts#137]
Some sources of Dizilab contain hardcoded subtitles, for instance, Supergirl season 1 episode 12.

**Comment by tknorris** [comment]
They shoudl be marked as such, but I'll check them.

**Comment by tknorris** [comment]
I don't see any reliable way to detect captions on dizilab, so you'll just have to take your chances with them.

**Comment by NitroXenon** [comment]
Ok thanks. Appreciate your amazing work!! :D
