### ISSUE TITLE
Moving SALTS DB to USB

### ISSUE THREAD

**Issue by mygithubuserid** [tknorris/salts#138]
Hi tknorris.
Before I ask my question I must join the group of people that have voiced appreciation for the work you've done and for sharing it. Both are truly great.

In the SALTS FAQ, under "How can I maximize performance for getting sources on slower hardware", option 4 says "try moving the SALTS DB off to a USB flash drive". Can you provide, or have you already  provided somewhere, some information on how to do this?

**Comment by tknorris** [comment]
http://kodi.wiki/view/HOW-TO:Change_settings_folder_for_Android

**Comment by mygithubuserid** [comment]
Thanks for the link, and sorry but I'm missing something. I need to confirm both of the following:
- which directory to move (".Kodi" in the HOW-TO)
- how to tell the system about the move ("xbmc_env.properties" in the HOW-TO).

I'm confused in part because, at the link below, in Section 2 (same topic as the link you provided), it says "The userdata folder can't normally be relocated completely, except on Android."

http://kodi.wiki/view/Path_substitution
