### ISSUE TITLE
"Movies" duplicating using SALTS with Trakt.tv on Kodi for Android

### ISSUE THREAD

**Issue by pyr8** [tknorris/salts#139]
All my movies have duplicated themselves under the "Movie" tab in Kodi. It looks like SALTS has included my local movie files on my NAS and duplicated them with the same movies available via the scrapers. Any ideas on how to remove the non-local instances?

**Comment by tknorris** [comment]
It sounds like the list you used as your sub list included all your local movies. You'll need to remove those from your sub list if you don't want them to be added. You can remove them from your list, then delete all the folders and strm files created, clean your library and then run a sub update.

**Comment by pyr8** [comment]
"sub list", do you mean Trakt.Tv subscription list?...Confused...do you know of a tutorial on solving this issues with step by steps? 

Thanks for getting back so fast!   :)

**Comment by tknorris** [comment]
Sub List = Subscription List. You must have created a SALTS Movie Subscription list, that's the only way SALTS creates strm files.

**Comment by pyr8** [comment]
I have uninstalled SALTS,removed the network locations for the Trakt.Tv sub lists and ran a cleanup on all video files. Are there any special files that will need manual removal before I re-install SALTS and reconfigure?

**Comment by tknorris** [comment]
Well, that was kind of overkill, but if you want to remove all trace them remove the plugin.video.salts folder under userdata/addon_data

**Comment by pyr8** [comment]
Ok, so I deactivated my Trakt.Tv account, then re-signed up for it using the same username and password. 

The entire account was reset and I had a blank slate to start with IE, there are no shows in the "Watchlist" on the website.  

I then reinstalled SALTS as well as the "Trakt.Tv List Manager" add-on in Kodi - (is the "Trakt List Manager" add-on needed? I have read conflicting info on this).

Configured both SALTS as well as entered credentials for "Trakt.Tv List Manager" add-on. All my TV shows are back in Kodi under "TV Show" as they were before, however they are not syncing _back_ to my https://Trakt.Tv account. I followed the tutorial for setting up SALTS and integrating with Trakt as per https://goo.gl/JcErFU

Thoughts?!

**Comment by tknorris** [comment]
What do you mean by "not syncing back to my trakt.tv account"?

**Comment by tknorris** [comment]
(btw, you don't need the trakt tv list manager for anything so I don't know why you installed that)

**Comment by pyr8** [comment]
The TV-Show list that is local on Kodi/SALTS is not syncing back to https://Trakt.tv.

**Comment by tknorris** [comment]
I think you might be very confused on how things should work. Maybe you should read the FAQ? Especially this one: https://github.com/tknorris/salts/wiki/Frequently-Asked-Questions#how-should-i-use-salts

**Comment by tknorris** [comment]
> The TV-Show list that is local on Kodi/SALTS is not syncing back to https://Trakt.tv.

There is no such thing as a list that is local in SALTS. All lists in SALTS are trakt.tv lists.

**Comment by pyr8** [comment]
I think you are very correct in the confusion part!  lol <sigh>

**Comment by pyr8** [comment]
I "think" I got it. When I initially setup SALTS/Trakt, I used the default "watchlist" for both movies and TV shows in Trakt. I did not setup separate "lists" for movies and TV Shows I already own.

**Comment by tknorris** [comment]
OK, spend some time reading and understanding the FAQ. If you read and understand it in full then things will work in a sensible way.

**Comment by pyr8** [comment]
One of the issues figuring this out was the "Movies, shows, seasons, and episodes **I plan to watch**" on the Trakt website. The language is misleading. One would think that shows "you want to watch in the future" should be saved to that "Watchlist".

**Comment by tknorris** [comment]
They are in as much as once you watch them they are no longer to be watched in the future. If you use trakt directly it makes sense since there's no reason to keep the things you watch on a list since trakt keeps track of them for you. You aren't the first person to be confused by the watchlist though.

**Comment by pyr8** [comment]
So for "ongoing" Tv shows, is it correct to have a separate "List" in Trakt, and for movies or one-off watching that I have identified as ones I want to watch in the future, use the "Watchlist" as opposed to creating a "list" called "movies" for instance? 

Right now I have the following "lists" in Trakt

1. Watchlist (default Trakt list)
2. Movies (a list I created for movies I want to watch down the road that will be streamed via SALTS)
3. TV (populated with all the TV programs I watch on an ongoing basis)

Should I just delete list number 2. and put the movies I want to watch in 1.?

**Comment by tknorris** [comment]
Really, it's up to you now that you understand how the lists and stuff work. Personally, I don't use library integration but I think it would make sense to use your watchlist as your movie sub list such that once you watch them. Personally, I think SALTS works better in native mode.

**Comment by pyr8** [comment]
So to use it in native mode and ignore movies/tv shows on my NAS... should I use "Set as Subscription List" and not use "Import from Collection" when setting up SALTS?

**Comment by tknorris** [comment]
It's all explained in the FAQ.

**Comment by pyr8** [comment]
I think I got it 95% sorted out. Still have 2 questions.

1. When you use the default "Watchlist" in Trakt for TV Shows, what happens if the season ends and you have watched all the episodes for that particular season. Will Trakt delete the show entirely for that season forcing you to re-add it for the following/upcoming season?

2. Is there anyway to have Kodi populate cover art or a snipit for recently updated Tv Shows on the main Kodi home screen that populated from SALTS/Trakt ? Right now it shows a blank square with the Name/season/etc.

P.S., how can I donate to the project?

**Comment by tknorris** [comment]
1. As soon as you watch a single episode of a TV Show, trakt will remove the whole show from the watchlist.
2. Scraping in the Kodi library is really a Kodi function and not really related to SALTS at all.

I don't accept donations,thanks for the thought though.

**Comment by pyr8** [comment]
Is there any plugin that you know of that will allow fanart for the scraped episodes?

What would you suggest is the best Android mobile app that supports both Movie and TV-Show lookup as well as user created list's in Trakt? I am using 2 at the moment, but neither support both TV shows and movies whilst utilizing user created lists. 

Thanks for all your help and timely replies....I would really like you to have a drink on me though!  :)

**Comment by tknorris** [comment]
That's not really a plugin function, that's purely in Kodi.

I just use the mobile trakt site I haven't found an android app that I'm happy with.

**Comment by pyr8** [comment]
I'll give the mobile app a try.

**Comment by pyr8** [comment]
Site rather.
