### ISSUE TITLE
MNE ERROR

### ISSUE THREAD

**Issue by ananias47** [tknorris/salts#142]
Hi
 I add the mne on my favorites (star on bottom  left corner)  but many times when i run it i have salt error and either i must run it again or kodi freeze and i must restartit. Also when i watch an ep from mne and i go back to mne again i have the same issues

Thnx

**Comment by bastardsandcheats** [comment]
A debug log of you opening the favorite will be needed.
https://www.tvaddons.ag/posting-error-logs-kodi/

**Comment by ananias47** [comment]
http://xbmclogs.com/pyo0xvalm

**Comment by tknorris** [comment]
It's a capacity issue w/ your hardware. You'll have to get better hardware to fix this.

**Comment by ananias47** [comment]
It is on rpi2 with openelec and 16gb sd

**Comment by tknorris** [comment]
Yep, MNE spawns a separate thread for for each show in your watched history and some systems can't take it. If you hide shows from your progress (e.g. completed shows) then this will reduce the number of threads. Otherwise, you just have to get a better box.
