### ISSUE TITLE
Search Skinshortcuts

### ISSUE THREAD

**Issue by Kodi-4-Beginners** [tknorris/salts#143]
Hi i there a way to ad the search option of movies and tv shows to the submenu of the home screen Kodi?

Grz .. Warez 

PS. Love your addon...

**Comment by tknorris** [comment]
That's a function of the skin. It's discussed at length in this thread: https://forums.tvaddons.ag/tknorris-release-repository/40187-skin-salts-enthusiasts.html

**Comment by Kodi-4-Beginners** [comment]
Thx!!
