### ISSUE TITLE
What to Expect for Performance

### ISSUE THREAD

**Issue by mygithubuserid** [tknorris/salts#144]
Hi tknorris, Thanks for pointing me in right direction ( #141 ). I did the following:
- took some timings within SALTS (prior to making changes)
- attached the USB HD, moved the Database dir onto it and created the appropriate symlink
- took some timings within SALTS (after making changes)

Below I've documented the captured timings, the procedures used and a summary of my config. Each of the timings before and after were all within a half second of each other, so I've only shown 1 of each below. 
Perhaps I'm hoping for too much. Would you expect someone in my position should be able to improve performance within SALTS, beyond what I'm seeing now?

**Procedure for attaching the USB external drive**
- Exit Kodi using the Exit option from the “power button” menu
- Login to OSMC
- Edit /boot/config.txt adding these lines
    - max_usb_current=1 (this insures Pi will provide current for HD)
    - rootdelay=5 (this is recommended by some to ensure NTFS driver has time to load)
- Shut down
- Plug the USB HD into the PI USB port
- Power up

**Moving Kodi Database Directory to External USB Drive**
- Exit Kodi
- Login to OSMC
- Make a directory on the external drive named “kodidb”
- Perform these steps from the Linux command line:
    - Stop Kodi service
           ($ sudo systemctl stop mediacenter)
    - Move the Directory
           ($ sudo mv /home/osmc/.kodi/userdata/Database /media/exthd/kodidb/Database)
    - Create Symlink
           ($ sudo ln -s /media/exthd/kodidb/Database /home/osmc/.kodi/userdata/Database)
    - Start Kodi service
           ($ sudo systemctl start mediacenter)
  
Note: At the end, prior to starting the mediacenter service, confirm that the symlink was created properly by listing the userdata directory contents and ensuring the Database folder is colored cyan and that it has a link associated with it. 
    
Command: sudo ls -ls /home/osmc/.kodi/userdata
    
Returned listing shows directory as: Database->/media/exthd/kodidb/Database

**Timings (both before and after, which is suspicious to me)**
- Launch SALTS: 9 sec
- Open TV Shows: 10 sec
- Open My Next Episodes (I have 21 shows): 15 secs
- Get Sources for next Blue Bloods episode (only Primewire and alluc enabled): 15 secs

**Summary of my config:**
- Raspberry Pi 2 with Kingston Class 10 MicroSD card
- OSMC (Debian Linux + Kodi)
- Confluence skin
- SALTS
- Trakt integrated
- Wired connection to internet router (speedtest.net says 16Mbps download speed)
- USB HD formatted with NTFS and labelled "exthd"

**Comment by tknorris** [comment]
The main thing is to look at your log and determine where the bottleneck is. If you see lots of SQL retries and DB locked errors, then the SD Card is the bottle neck and moving the DB to a faster disk will help. Moving the DB isn't going to help the time it takes to Launch SALTS or to open TV shows, but will help when getting sources, MNE, and Set Related Url.

**Comment by mygithubuserid** [comment]
Is there some improvement that would improve the speed of launching SALTS or opening TV Shows, something that could be done on the Pi or maybe going to another computer with more RAM, faster CPU or faster system drive?

**Comment by tknorris** [comment]
Post a log of all these functions being executed and I'll tell you where your system spends most of the time. You can remove the "Other Lists" from the section menu to speed things up when opening the TV Show and Movie menu.

**Comment by mygithubuserid** [comment]
Kodi logs attached. One had debugging enabled. Same SALTS functions executed for both.
[kodilogdebugfalse.zip](https://github.com/tknorris/salts/files/128314/kodilogdebugfalse.zip)
[kodilogdebugtrue.zip](https://github.com/tknorris/salts/files/128315/kodilogdebugtrue.zip)

**Comment by tknorris** [comment]
I took a look at your log and it looks like the way I'm doing internationalization is triggering some odd behaviour in Kodi. When you open TV Shows, Kodi reloads the translated strings over and over for the first 8 seconds, then my code itself only executes for 2 seconds. I think I know what is causing the problem and I'll put a potential fix in the next build. Let me know if the performance is better in 2.0.2 (still in dev)

**Comment by mygithubuserid** [comment]
Excellent. I'll keep an eye out for it. Thanks a lot for all your time.

**Comment by mygithubuserid** [comment]
If it would help to test the potential fix on my setup prior to releasing 2.0.2 I'd be happy to do that. I can count my Kodi add-ons on one hand so it's a pretty clean build.

**Comment by tknorris** [comment]
Sure, if you know how to install from github. I can already tell you though that it's significantly faster. My dev machine is fast, but I notice a pretty big difference.

**Comment by mygithubuserid** [comment]
Well, it sounds like the change you've made is likely to help, so I probably don't need to install a pre-release version just to test. However, I've never installed from github, and I would like to understand the process, so I'll try. Do any of your recent commits include the fix?

**Comment by tknorris** [comment]
You can just use "download zip" from the main page of the repository and the install that zip in Kodi. The main thing is to make sure you remove that version before going back to a repo version. I'll push a new version within the next 24 hours, so you just may want to wait.

**Comment by mygithubuserid** [comment]
Thanks for the tip on how to install, and for the tip on how to roll back, but since you'll be pushing out the new version soon I won't need to use them, I'll just wait. I did take a new set of timings, and I'll leave my setup as-is until the update comes out. Afterward I'll capture another set of timings for comparision, and I'll post both sets.

**Comment by mygithubuserid** [comment]
Well, I see you've been busy, 2 version bumps in 1 day. I've been looking for a change in the tknorris release repo but, since you've now bumped version a second time and no version number change appers there, I'm thinking I might be looking in the wrong place. Would you please tell me where I should be looking to confirm a new release has been officially published?

**Comment by tknorris** [comment]
The release version is updated rarely as it's considered stable. The beta is the one I update regularly but is considered less stable. Read this first post to get my beta repo installed: https://forums.tvaddons.ag/tknorris-release-repository/26867-stream-sources-aka-salts-beta-thread.html

**Comment by mygithubuserid** [comment]
Attached are the timings I captured, 2 sets for each of versions 2.0.1 and 2.0.3. All 4 sets were captured after a system reboot. Clearly your changes in 2.0.3 are a big improvement, almost a 60% average gain  for all. And with many of the timings being near 4 seconds, they're accuracy is likely impacted by the ability of my hand to stop the stopwatch quickly.

At this point the build as a whole - meaning Pi, OSMC, SALTS and Trakt - make a pretty slick media center. And SALTS is my only video add-on.

![capture](https://cloud.githubusercontent.com/assets/16868982/13080902/e5d0ea02-d487-11e5-929a-3266764a7235.JPG)

**Comment by tknorris** [comment]
Cool, I'm glad it's better.
