### ISSUE TITLE
temporary trakt error

### ISSUE THREAD

**Issue by luiselmau** [tknorris/salts#146]
my salts just stop working. it say : temporary trakt error : http error 504 gateway time out.
do you know what this may be?

thank you.

**Comment by tknorris** [comment]
trakt server API performance issues. Nothing can be done, just wait.

**Comment by luiselmau** [comment]
but i can´t use the addon without trakt?

**Comment by tknorris** [comment]
No.

**Comment by luiselmau** [comment]
thank you
