### ISSUE TITLE
Incluse Watchlist in My Next Episodes - Not working

### ISSUE THREAD

**Issue by mygithubuserid** [tknorris/salts#147]
I have 28 shows listed in My Subscriptions and yet, regardless of whether I enable or disable the setting called "Include Watchlist in My Next Episodes", 22 are listed in MNE.

I cross-checked my list, and did a spot check of the shows not in MNE, and none of the omitted shows had episodes marked as watched.

**Comment by tknorris** [comment]
My Subscriptions is for Library Integration, not MNE. MNE is a combo of watchlist + watched history. In other words, as you watch shows, they will automatically show up in MNE. The only way to make them show up w/o watching them is to add them to your watchlist.

**Comment by mygithubuserid** [comment]
They're in my watchlist. When I go to My Lists and choose my custom watchlist, all 28 shows are listed. If I've included a show in my watchlist, but never watched an episode, should Season 1 Episode 1 be listed in MNE?

**Comment by tknorris** [comment]
If you have "Include Watch in MNE" it should. Also you said "custom watchlist" You have to use the standard watchlist, not a custom list.

**Comment by mygithubuserid** [comment]
I see. I was using a custom watchlist because I believe Trakt automatically removes watched items from the standard watchlist.

If I must use the standard list, how is it that MNE is presently listing shows from my custom list (albeit only the ones with a watched episode)?

**Comment by tknorris** [comment]
Because of what I said earlier. MNE is a combo of your watched history + watchlist (if enabled). You don't really need to keep a custom list of what you watch, Trakt/SALTS will do it for you based on what you watch.

**Comment by mygithubuserid** [comment]
Ok, I think I'm now a bit more clear on how it's intended to work. Thanks.

What do you recommend for backing up the watched history?

**Comment by tknorris** [comment]
Personally, I don't. If you wanted, you could use the csv export on the watched history page. To me it's just the things I watched. I didn't have a record of them before trakt, so to not have them again wouldn't be the end of the world.
