### ISSUE TITLE
Very slow getting sources

### ISSUE THREAD

**Issue by ananias47** [tknorris/salts#150]
The last days i have very slow getting sources although i have only enabled 20 scrapers and in most of the time are timeout

**Comment by tknorris** [comment]
need a log.

**Comment by grant2258** [comment]
I noticed this too main culprit for me was alluc.com think they might have changed the website layout or something. disable that see how  you go.

**Comment by tknorris** [comment]
closed for lack of response.

**Comment by ananias47** [comment]
Yes i disable alluc and now its ok
