### ISSUE TITLE
TV shows in "My Next Episodes" list can't be removed manually

### ISSUE THREAD

**Issue by uniZero** [tknorris/salts#151]
As far as I can tell, there's no way to remove a TV series from the "My Next Episodes" menu unless the user:

+ marks unwatched episode(s) as "watched"
+ marks watched episode(s) as "unwatched"

Example use case:  

1. You watch a TV show pilot but aren't interested in watching anything further.  
2. SALTS adds this TV series to your "My Next Episodes" list.  
3. Your "My Next Episodes" becomes larger and harder to navigate over time  

Some ideas for addressing this issue:  

+ a `remove show from list` right-click context menu option, where applicable
+ a "My Next Episodes" list manager within the addon settings menu

**Comment by tknorris** [comment]
You are mistaken. Mark it hidden on the progress page of the trakt site. Note your hidden list is cached for 2 hours so updates won't be seen immediately unless you force refresh MNE.

**Comment by uniZero** [comment]
Thanks. I couldn't find that information when I looked beforehand.

However, I don't think users should have to leave Kodi and visit the Trakt website directly to achieve such functionality. It's not obvious by any means.

**Comment by tknorris** [comment]
Sorry, that's how it works.
