### ISSUE TITLE
Furk time out

### ISSUE THREAD

**Issue by ronney67** [tknorris/salts#152]
I have an account from Furk.  I see in Salts that I can enable  the scraper and put in my account details. When I click  on a movie or a TV show,  it says nothing found.  In another addon,  like specto,  it works and find the sources.  Can you please solve this,  because I like your addon.  Thanks in advance!

**Comment by bastardsandcheats** [comment]
I can't check this because i don't have a furk account.
furk.net seems to no longer allow http connections, you can try setting the furk base url to https. 
That may work, if it doesn't the scrapper will need updated

**Comment by tknorris** [comment]
I'll check it when I get a chance, but as recently as last night it was working fine for me. It would be better if you posted a log of gettin sources.

**Comment by ronney67** [comment]
I have checked again and I fill in again my account settings and it works now.  Strange because I was sure that everything was ok.  So goodbye Specto
