### ISSUE TITLE
Add movie to favorites

### ISSUE THREAD

**Issue by iaai** [tknorris/salts#153]
Would you please consider adding the ability to add a movie to favorites or a whole tv show with all their links inside, instead of being able to just add one link to favorites. 

Thanks

**Comment by tknorris** [comment]
You can already add movies and tv shows to favorites. I don't understand what you are asking.

**Comment by iaai** [comment]
As you can see in this screen shot there is no option to **add to favorites**:
`http://i.imgur.com/c2yrx70.jpg`

and this option exist in other addons as you can see in the following screen shot:
`http://i.imgur.com/NT8vzcU.jpg`

Thanks.

**Comment by tknorris** [comment]
You have to link SALTS with your trakt account to add to favorites.

**Comment by iaai** [comment]
It's working, thanks, although it would be nice if we had the option to add it to favorites locally without needing to have an account just to add it to favorites.

Thanks for the great work.
