### ISSUE TITLE
Salts HD Lite

### ISSUE THREAD

**Issue by xsmashx88x** [tknorris/salts#156]
um not sure if you know but someone forked your salts http://www.mediafire.com/download/7337iqx0zj8ipq3/plugin.video.saltshd.lite-1.0.116.zip seen this on a channel and seems to be making its way around... not sure what all he he changed as i will not install this

**Comment by tknorris** [comment]
I'm aware. Last time I looked at it, the person changed one line in one file to prevent most scrapers from loading most of the scrapers. You can do the same by disabling them in addon settings. I have no opinion on it. The SALTS source is GPL and anyone is free to copy as they so wish.

**Comment by xsmashx88x** [comment]
if people want support for this they need to contact this dude not you right? now that he is messing with your add-on

**Comment by tknorris** [comment]
Yes, I won't support anyone who is using it but not out of spite, but simply because if he makes changes he's responsible for them. I have no way or knowing (or caring) what changes he has made that may or may not produce different outcomes that my code.

**Comment by xsmashx88x** [comment]
okay thank you for that reply :)

**Comment by Kodi-4-Beginners** [comment]
By the way .. i made the mod on the addon...

**Comment by tknorris** [comment]
No Comment.
