### ISSUE TITLE
add an option to filter out h.265 encoded content

### ISSUE THREAD

**Issue by djbijo** [tknorris/salts#158]
Hi, i've noticed lately there's a lot of h.265 encoded content which the small boxes can't handle (cubox-i, RPI2 etc)
is there a possibility to add filter so i won't have to manually select a source without "265" in it's name?

thanks
gil

**Comment by tknorris** [comment]
Sorry, I'm not interested in doing that. All my HW plays x265 just fine.

**Comment by djbijo** [comment]
:(
i noticed theres a tag (x265) or (1080p-x265) in the sources selection.
can you please point me to the field containing this string so i can try and add this filter on my own?
iv'e been seeking through the code and couldn't find it.

thanks ,
Gil

**Comment by tknorris** [comment]
Unfortunately, it varies from scraper to scraper, that's one of the reasons I'm not interested in adding it. I'd have to go back and add the logic in a consistent way which means retesting all those scrapers and all for no benefit to me since all my HW works fine w/ x265.

**Comment by djbijo** [comment]
i see. ok 10x anyways

**Comment by bastardsandcheats** [comment]
If you do want to do something yourself you can move things to the bottom of the sort. 
There are a few different ways:

utils2.py
line
326(salts v 2.0.8)
def get_sort_key(item):
`def get_sort_key(item):
    item_sort_key = []
    for field, sign in SORT_FIELDS:
        if field == 'none':
            break`

Just move everything tagged X265:
`
def get_sort_key(item):
    item_sort_key = []
    for field, sign in SORT_FIELDS:
        if 'X265' in item['class'].format_source_label(item):
            item_sort_key.append(0)
`

Move things tagged with X265 or HEVC/X265 in their URL (works with a few hosters):
`
hevc = ("hevc", "h.e.v.c", "x265", "x.2.6.5" )
def get_sort_key(item):
    item_sort_key = []
    for field, sign in SORT_FIELDS:
        if 'X265' in item['class'].format_source_label(item) or any(s in (item['url'].lower()) for s in hevc):
            item_sort_key.append(0)
`

move anything with X265/HEVC in the label - this will include things from santaseris that aren't really HEVC, but it will also include things from alluc that could be.
`
def get_sort_key(item):
    item_sort_key = []
    for field, sign in SORT_FIELDS:
        if any(s in (item['class'].format_source_label(item).lower()) for s in hevc):
            item_sort_key.append(0)
`

Move anything with X265/HEVC in label or URL
`
hevc = ("hevc", "h.e.v.c", "x265", "x.2.6.5" )
def get_sort_key(item):
    item_sort_key = []
    for field, sign in SORT_FIELDS:
        if any(s in (item['class'].format_source_label(item).lower()) for s in hevc) or any(s in (item['url'].lower()) for s in hevc):
            item_sort_key.append(0)
`

I prefer just doing anything tagged X265 by salts or with X265 in the url
Could miss a few things but won't include anything that's not hevc

**Comment by djbijo** [comment]
thanks! i tried the first option and it worked, only after i added an option to enable/disable it it didn't work so well.
also, i noticed that all the sources that were moved to the bottom of the list(x.265) were not playable at all.
i will keep digging later
