### ISSUE TITLE
scrapers timeouts

### ISSUE THREAD

**Issue by ananias47** [tknorris/salts#159]
every time i have alluc and mtvs timeouts

log:http://xbmclogs.com/pukuvpksv

thnx

**Comment by tknorris** [comment]
sign up for account and enter your details for alluc; mtvs is just slow.

**Comment by ananias47** [comment]
so i must make an acc on alluc.ee??

**Comment by tknorris** [comment]
looks like. the SALTS api key is getting redirected.

**Comment by ananias47** [comment]
so its scraper problem??

**Comment by tknorris** [comment]
no, it looks like alluc isn't offering free api keys anymore so the scraper won't work w/o a uid/pw

**Comment by ananias47** [comment]
so i must disable it so not to hung out??

**Comment by tknorris** [comment]
either disable it, or sign up for an account. your choice.

**Comment by ananias47** [comment]
i cant find anywhere the signup

**Comment by tknorris** [comment]
http://accounts.alluc.com/

**Comment by ananias47** [comment]
man u are the best one more remove disimag because there is no longer working because of capatcha


thnx again

**Comment by tknorris** [comment]
not all countries have the captcha.

**Comment by ananias47** [comment]
aha can i do something like proxy to think thgat i am in turkey???

**Comment by tknorris** [comment]
I don't do proxies because they always go down and you have to keep finding new ones.

**Comment by ananias47** [comment]
one more the url search that i have fix for a tv series is there a way to import it on salts??

**Comment by tknorris** [comment]
You could use the DB Import on the Database tab of addon settings. You can do an export to see the format of the csv file.

**Comment by ananias47** [comment]
ok thnx for ur time and keep up the good work
