### ISSUE TITLE
Only X265 1080p results by dd.tv

### ISSUE THREAD

**Issue by ronney67** [tknorris/salts#160]
The scraper dd.tv gives only the X265 1080p as results.  Is there a possibility that you can add the 1080p webdl x264?  Thanks in advance!

**Comment by tknorris** [comment]
If you are using the release version, you can remove the quality vlaue from the related url to see all values. The beta version of SALTS shows you all results of lesser or equal quality to the best one found.

**Comment by ronney67** [comment]
How do I do that?  I use the release version

**Comment by tknorris** [comment]
Read the FAQ.

**Comment by ronney67** [comment]
I have read the faq. Can change anything. Blank results.  DD.tv only gives x265

**Comment by tknorris** [comment]
you can try posting a log. It's working normally here.
