### ISSUE TITLE
How to reset Authorized Trakt User

### ISSUE THREAD

**Issue by mygithubuserid** [tknorris/salts#161]
Hi,
How can I reset the Authorized Trakt User? I've tried using the Defaults button, which seem to clear the old value, but I don't get an option for entering a new value.

**Comment by tknorris** [comment]
Go through the auth process again to auth a new user

**Comment by mygithubuserid** [comment]
That worked, this time. I had tried that yesterday but I couldn't get it to work. Your response did help just by confirming there wasn't some other approach I should have been using.

Do you think that, before redoing the auth process, it would help ensure success if one was to deactivate SALTS in Trakt?

**Comment by tknorris** [comment]
no, that should have no effect.
