### ISSUE TITLE
Trakt Incompatible

### ISSUE THREAD

**Issue by PAULAAJ2601** [tknorris/salts#163]
Hi, not sure if you can help.  Had to do a fresh install of Kodi and set everything up again as mine died.  I've installed the beta versions of SALTS and got it all authorised with my TRAKT account. Ive just noticed after doing the subscription update it does when starting up that it didn't do the TRAKT Sync of TV & Movies as it usually does.  When going in to my addons it is now showing that the TRAKT addon is incompativle due to dependencies not met.  I've had this before and it seems to just sort itself so I'm hoping it does again, however can you explain if and how this will affect my use of SALTS?  I use it on two different machines so will they no longer be 'synced' as such? Many thanks

**Comment by tknorris** [comment]
The newest trakt addon is only compatible with Jarvis only. If you download and install the version from here: http://ftp.halifax.rwth-aachen.de/xbmc/addons/isengard/script.trakt/ it should work fine.

**Comment by PAULAAJ2601** [comment]
Tried this but it didn't work still saying dependencies not met. Version 
3.05beta working fine on other box, both running kodi 14.8

**Comment by tknorris** [comment]
I thought you were running Isengard. I'm not sure if there is a trakt addon that's still compatible w/ Helix. Helix is pretty old at this point.

**Comment by PAULAAJ2601** [comment]
Hi, no probs, apparently DROIDPLAYER will be updating their firmware to 
16 or 17 in the next month, or so they tell me.  Just slightly confused 
as to why its working on one and not the other.  Hey ho, guess I'll just 
wait until they update.  Thanks for your responses, very much appreciated
