### ISSUE TITLE
Source list disappearing 

### ISSUE THREAD

**Issue by vindrace** [tknorris/salts#164]
Not much of an issue other than a QoL change. By default when selecting a movie or episode the source list will appear and when you select your source of choice the list disappears. This is fine most of the time but if a link fails you're left with reloading the sources and trying another. Somehow about 6 months ago on my pc I managed to get the source list to stay up until the source starts to play. Meaning if a source fails the list is still there and I can simply go to the next. Now im trying to get the same results on a fireTv and for the life of me i cannot find what i did. I've looked through both pc and firetv salts settings and both seem to be the same. any idea?

**Comment by tknorris** [comment]
Switch to directory mode.

**Comment by vindrace** [comment]
Thank you. You do amazing work
