### ISSUE TITLE
Update to 2.0.10

### ISSUE THREAD

**Issue by PAULAAJ2601** [tknorris/salts#165]
Hi, just updated to 2.0.10 and cannot get into SALTS, keep getting script error and does not even go into the SALTS menu.  Still running previous version on another box and that's working fine.  Is this another case of it not being compatible with my running helix 14.8.  Just want to check before I spend ages trying to sort it out and doing clean start on my droidplayer.  If this is the case, is there anywhere I can access the previous version (2.0.9) so I have a working copy until droidplayer update to 16 or 17.  Many thanks

**Comment by tknorris** [comment]
Update to 2.0.11.

**Comment by PAULAAJ2601** [comment]
Updated to 2.0.11 and can now at least get into menu.  However, even though it runs through the updating tv shows process I can not access MNE or Calendar.  I can get into the list of TV Shows in my lists.

**Comment by tknorris** [comment]
Post a log.

**Comment by PAULAAJ2601** [comment]
Here you go


http://xbmclogs.com/pxe3rtgao

Cheers

**Comment by tknorris** [comment]
Thanks. It's a code bug. There's no work around for now. Your best bet is probably to reinstall the last build that worked for you and turn off autoupdates for now.

**Comment by PAULAAJ2601** [comment]
ok the last one that worked for me was 2.0.9 - how do i get that?

**Comment by tknorris** [comment]
you can download it manually from the beta repo: https://github.com/tknorris/tknorris-beta-repo/tree/master/zips/plugin.video.salts

Click the "View Raw" button and you will get prompted to download it, then move it to your system however you do that and use Install from Zip.

**Comment by PAULAAJ2601** [comment]
Cheers, will try that now

**Comment by tknorris** [comment]
Yeah, the next build will be an attempt to fix these issues. So, test it out once I push it and let me know if you still have problem.s

**Comment by PAULAAJ2601** [comment]
Hi, FYI just updated to 2.0.13 and all working fine
