### ISSUE TITLE
2.0.17 crashes Kodi

### ISSUE THREAD

**Issue by thwaller** [tknorris/salts#167]
With this new update, as soon as I try and open the addon, Kodi freezes for a short time then crashes/closes with no errors or messages. Using Kodi 16.1 RC1. If you are not aware of this and need further information, let me know. Aside from SALTS, there are no issues in Kodi.

**Comment by tknorris** [comment]
I need a log of the crash.

**Comment by thwaller** [comment]
[kodi.old.log.txt](https://github.com/tknorris/salts/files/172480/kodi.old.log.txt)
Please delete the file when done, thanks.

**Comment by tknorris** [comment]
Since my dev machine is the same basic platform as you and I'm not seeing this issue, it must be something specific to your install. No one else has reported the problem either. Try uninstalling SALTS and reinstalling it, you might have gotten corrupt somehow. Have you tried to backlevel to 2.0.16 and seeing if the error still happens? If so, then I don't think it's SALTS causing it. I didn't really change anything in 2.0.17 that should cause a crash like this.

**Comment by tknorris** [comment]
The relevant error in your log is this:
`12:04:27 T:139684570728576   ERROR: exception in CApplication::FrameMove()`

That's a system level error that can frequently be caused by bad video drivers. When looking at your log, SALTS never even actually gets to execute, Kodi crashes when it tries to start the script. I don't think it's a SALTS issue.

**Comment by thwaller** [comment]
All was fine before the update. Do you have the 2.0.16 I can go back to? All works fine until I try and open SALTS, so if it is a driver or something similar, only SALTS causes the issue.

**Comment by tknorris** [comment]
You can download 2.0.16 from here: https://github.com/tknorris/tknorris-beta-repo/tree/master/zips/plugin.video.salts

If you go back to 2.0.16, and it doesn't cause the error, then go back to 2.0.17 again and see if the error comes back.

**Comment by thwaller** [comment]
Will do. I just tried other addons and they are all fine. Exodus, 1Channel, Live Mix, Vevo, etc. I will let you know.

**Comment by thwaller** [comment]
2.0.16 is crashing now, just as the 2.0.17. Not sure what else to test. Something happened that effects only SALTS from what I can see.

**Comment by tknorris** [comment]
suggest this then: delete the folders:
.kodi/addons/plugin.video.salts folder
.kodi/userdata/addon_data/plugin.video.salts folder
.kodi/addons/packages

then restart kodi, reinstall SALTS and see if the crash goes away
Note, you will lose all your SALTS settings when you delete addon_data/plugin.video.salts so consider backing up that one before deleting it.

**Comment by thwaller** [comment]
I have just tried My Subscriptions to use SALTS as an alternate addon. It also failed, but did not kill Kodi. I will try as you suggested in a bit when I have a min. Any idea why only SALTS would error, assuming it is a system issue and not a SALTS issue?

**Comment by tknorris** [comment]
Not off hand, from your log it doesn't look like Kodi ever even gets to executing the SALTS code, so it's odd. Within the first 3-4 lines of code that SALTS executes it prints out the Version/Query information and that info isn't showing in the log.

**Comment by thwaller** [comment]
Ok, based on what I am seeing and the ideas not working, I am assuming that it is a good possibility that something else happened around the same time as this update. You mentioned the possibility of something wrong with the video driver. How would I look into this? Although somehow this involves the SALTS addon as it is the only aspect of the whole box that has an issue, the reverting to older version not fixing it does not point me directly to SALTS either. Any thoughts would be appreciated.

**Comment by tknorris** [comment]
did you try my suggestion of deleting the stuff I mentioned earlier?

**Comment by thwaller** [comment]
yes, sorry, I was saying that with the ideas not working. Should have been more clear.

**Comment by tknorris** [comment]
Try this: stop kodi; rename .kodi to .kodi-back; install SALTS and see if it works. If it does, then you know it's some kind of config that's causing the problem.

You can also check your recent apt history to see what updates have been done on the box. That history is in /var/log/apt/history.log

**Comment by tknorris** [comment]
Are you using an alternate skin? If so, try switching back to Confluence.

**Comment by thwaller** [comment]
No, I have a modified Confluence installed, but not using it. I never found the skins to be desirable much. I will do the rename and see, basically making Kodi fresh. I am still puzzled at how/why this is only a problem with SALTS. If it is not even executing the code, why does clicking on it cause the crash....and no other plugin.....

**Comment by tknorris** [comment]
I don't have a good answer for you. If I was sitting at the box I could do some kind of forensics, but without direct access it's just a guess. Like I said though, my dev box is identical to yours: Ubuntu 15.10; Kodi 16.1 RC1; SALTS 2.0.17 and I'm not having an issue.  It also doesn't appear anyone else is having the issue as no one in the beta thread has mentioned it and 2.0.17 has been out for > 24 hours.

**Comment by thwaller** [comment]
Ok. Thanks for all the help. I guess I was in the wrong place, can you provide the URL for the beta thread? I was able to resolve the issue, I uninstalled the modified Confluence skin. Thanks for the hint to look at that. Not sure why, but it was not active, just installed.

**Comment by tknorris** [comment]
https://forums.tvaddons.ag/tknorris-release-repository/26867-stream-sources-aka-salts-beta-thread.html

**Comment by thwaller** [comment]
Would you prefer beta release issues be posted there?

**Comment by thwaller** [comment]
For reference, I have also noticed by doing the above that when I add a selection to the library from the SALTS plugin, the speed in which it is added is faster. It prior took about 5-10 seconds, it now takes just 1-2 as it is with other plugins.

**Comment by tknorris** [comment]
> Would you prefer beta release issues be posted there?

Either is fine. There's a lot more dialog that goes on at the forum. I'm not sure why that alternate skin was causing issues w/ SALTS. That's pretty weird.
