### ISSUE TITLE
database shortcut

### ISSUE THREAD

**Issue by abeksis** [tknorris/salts#170]
Is there a way to create a shortcut for deleting files of db? 

Shortcut without the File Manager. Link directly from Skin Settings

**Comment by tknorris** [comment]
you can use the same plugin:// url that SALTS uses when you select Reset DB from addon settings.

**Comment by abeksis** [comment]
Can you give me an example?

**Comment by tknorris** [comment]
turn on debug; select reset db from addon settings and you'll see the correct plugin url. FYI, I have no interest in supporting someone making a wizard/build.

**Comment by abeksis** [comment]
Thank you

**Comment by abeksis** [comment]
RunPlugin(plugin.video.salts,-1?mode=reset_db)

not working for me
