### ISSUE TITLE
Source selection

### ISSUE THREAD

**Issue by thwaller** [tknorris/salts#172]
When selecting a source with multiple selections, ex. (REA, PRE), all I get is a blank dialog box. There is no option for me to select a source. I assume I have something set wrong? Sources with only one option, ex. (REA) and those that are not 'green' work fine to be selected.

**Comment by tknorris** [comment]
upload a log and post a screenshot

**Comment by thwaller** [comment]
![screenshot at 2016-04-12 20 11 51](https://cloud.githubusercontent.com/assets/13359198/14480112/67517abc-00eb-11e6-97cf-0b1e2c98b34a.png)
![screenshot at 2016-04-12 20 14 38](https://cloud.githubusercontent.com/assets/13359198/14480113/675c22aa-00eb-11e6-9c81-ea5851b7e3c3.png)

[kodi.txt](https://github.com/tknorris/salts/files/216240/kodi.txt)

Here are requested files. Please delete the files once you have them, I did not edit or filter them. Thanks.

**Comment by tknorris** [comment]
It's a problem w/ the all debrid resolver. Disable or increase it's priority for now. I'll have a fix in the next urlresolver release.

**Comment by thwaller** [comment]
I see. Will do. Thanks.

**Comment by thwaller** [comment]
Hmmm, where can I do this? I am not seeing this in the addon settings.

**Comment by tknorris** [comment]
It's in urlresolver settings.

**Comment by thwaller** [comment]
LOL! yeah, yeah. Sorry, got it.

**Comment by thwaller** [comment]
> I'll have a fix in the next urlresolver release.

When would such release be expected?

**Comment by tknorris** [comment]
I have no plan for one right now. The only change pending is this one.
