### ISSUE TITLE
Add new scrapper for anime hd.

### ISSUE THREAD

**Issue by yepmouidriss** [tknorris/salts#173]
salts is the greatest addon I know for movies and tv shows at the moment, it is not possible to add scappers for animes synchronised with trakt and tvdb seaspn order. it will be so nice. thank you.

**Comment by tknorris** [comment]
There are two problems 1) I don't want anime and 2) I haven't seen any anime that isn't counted in absolute numbering rather than season/episode numbering as trakt does.
