### ISSUE TITLE
Captcha letters hiding.

### ISSUE THREAD

**Issue by romanoh** [tknorris/salts#82]
The opening stream box in left upper hides the captcha letters, so i cant see the full phrases.
Android system OUYA.

Great work @tknorris

**Comment by tknorris** [comment]
Can you show me a screenshot so I can see what you mean? Normally the image comes up in front of the opening stream window.

**Comment by romanoh** [comment]
http://img540.imageshack.us/img540/8332/PKop8I.jpg

**Comment by tknorris** [comment]
Ah, it looks like you aren't using the default skin, are you?

**Comment by romanoh** [comment]
No, i usualy use this one: https://github.com/stoli/Metropolis

**Comment by tknorris** [comment]
I'll think about the captcha problem, I'm not sure I'll be able to fix it. In Confluence the opening stream doesn't pop up there.

You can limit the sources to only HD, but you can't only see movies that have HD sources.
