### ISSUE TITLE
Migrate to trakt PIN auth

### ISSUE THREAD

**Issue by tknorris** [tknorris/salts#86]
http://docs.trakt.apiary.io/#reference/authentication-pin/authorize-application

**Comment by mgonzales71** [comment]
FYI - the new PIN auth in the latest version of SALTS does not provide a human readable URL in the skin Titan Helix (Beta).

I had to drag out my iPhone and scan the QR code - ack!  :-)  

Granted this could possibly be skin related (again I am using Titan Helix Beta skin) - but the Trakt script beta7 PIN auth for Kodi displayed both a URL and QR code just fine even on this skin.

I know the baseline is confluence skin support but you may want to consider a more simple dialog for wider skin support - again just wanted to pass this along as an FYI.  (and yes it looks perfect under confluence skin)

![screenshot000](https://cloud.githubusercontent.com/assets/6510026/7443223/cf7d77e2-f0ef-11e4-8464-721c4a97e1c4.png)

In case you have not used the skin....

Stable skin is in official Kodi repo.

Git: https://github.com/marcelveldt/xbmc.skin.titan

Beta repo: http://cdn.mediabrowser.tv/downloads/addons/xbmb3c/kodi-beta-repo/repository.beta.mediabrowser.kodi-1.0.1.zip

Again - just an FYI ... I re-worked the pin dialog in trakt script beta 7 to better match the look and feel of the skin (screenshot in PR - https://github.com/marcelveldt/xbmc.skin.titan/pull/46) and I can do so with your addon - wondering if this will happen with all new addons that support the new trakt pin auth method. yikes. hehe :-)

Anyway - thanks for your great work on SALTS and Trakt v2 API support!

Mario

**Comment by tknorris** [comment]
Yuck, it looks like the text scrolled out of the text box that I allocated. In Confluence it was fine. One workaround would be to switch to Confluence long enough to authorize then switch back to your skin.

One thing I can do is switch to a smaller font to give more space to other skins before it bleeds out of the bounding box. For example, in Confluence, the text fits in all those buttons.

**Comment by mgonzales71** [comment]
oh crap I accidentally deleted - stupid mouse and no undo on Git! lol

yea - plus I find the 720 vs 1080 based skins always have glitches.

Thanks - again - and sorry for the klutzy mouse hitting that tiny "x" ;-)

**Comment by mgonzales71** [comment]
and I was able to auth just fine - I knew what was going on when I saw the dialog.

you know the strangest thing - I was having so many many issues with trakt support under SALTS and Genesis until I realized that auth with email and password caused problems where username and password worked like magic.  now we have PIN auth to muddy more waters after the fun break neck abrupt turn that v2 api's gave everyone.

**Comment by tknorris** [comment]
The username/email thing confused a lot of people. It's irrelevant now though because I replaced all the api calls with "me" rather than the username. So, if we were still using a username either would work, but since we aren't it doesn't matter.

**Comment by mgonzales71** [comment]
yea that is one in the plus column for Pin Auth :)

thanks for all your hard work and looking into the textbox / text display issue.

Just put the URL in the IMG - problem solved LOL

**Comment by tknorris** [comment]
Hey, I was looking at this a bit tonight and I was able to resolve most of the issues with your skin and the SALTS PIN window. One thing I found is if you add a font declaration for font12 then it fixes the text so it's visible. I added this to your font.xml to so that the text fits in the bounding box.
```
<font>
    <name>font12</name>
    <filename>Arial.ttf</filename>
    <size>23</size>
</font>

Two things that are not working that I couldn't fix are the window header text (doesn't show), and the text entry focus (also doesn't show). Let me know if you know how to fix those.

**Comment by mgonzales71** [comment]
Yea - that is probably a good font definition to have in the skin - I will update and send a Pull Request to Marcel for the skin.  I will look into the other two things - it may require a change in one of the includes xml files for the skin.  thanks so much for going above and beyond on this one! :)

**Comment by tknorris** [comment]
No problem, I also swapped the two paragraphs so that at least when the text goes beyond the bounding box the meaningful piece (i.e. the PIN url) will still show up.

**Comment by mgonzales71** [comment]
thanks again for the help - open an issue on the skin https://github.com/marcelveldt/xbmc.skin.titan/issues/57 in case you were bored and wanted to follow along :)
