### ISSUE TITLE
kodi is stuck after searching for sources

### ISSUE THREAD

**Issue by djbijo** [tknorris/salts#89]
version 1.0.1
platform: openelec 5.0.8 on cubox-i4
when clicking on an episode to watch, after all sources are found kodi hangs and doesn't show list of sources to choose from.
log: http://pastebin.com/Yhvppezy

**Comment by tknorris** [comment]
You should be able to work around this problem by switching to directory mode under the Source Management tab. I can guess what the problem is already.

**Comment by djbijo** [comment]
this work around doesn't always work
and also, when using library integration there is no directory mode...
is there a way to downgrade to 1.0.0 until this is solved?

**Comment by tknorris** [comment]
You can download the older zips from here: https://github.com/tknorris/tknorris-beta-repo/tree/master/zips/plugin.video.salts

Just install one of the older ones and turn off auto-updates until I can fix it.

**Comment by djbijo** [comment]
cool 10x

**Comment by tknorris** [comment]
I just pushed 1.0.2 to fix your issue. Let me know if it's fixed. I had to remove the progress dialog from the get sources function.

**Comment by djbijo** [comment]
it's fixed, thanks!
