### ISSUE TITLE
Problem registering « Watched » state on Trakt.tv after completing an episode from « My Next Episode » section

### ISSUE THREAD

**Issue by philippedurocher** [tknorris/salts#90]
When I'm watching an episode from « My Next Episodes » section in SALTS, I always need to use the contextual menu « Mark as watched » after I complete my episode (even if I ffwd to the end of it). I guess SALTS should register the « Watched » state in Trakt.tv. The checkmark appears after my watched episode but not on Trakt.tv.

Keep up the good work! I discovered 2 weeks ago your addon and I love it! I also discovered trakt.tv thanks to SALT and I love it too! Great idea and great integration. Thank you.

**Comment by tknorris** [comment]
Do you have the official trakt add-on installed and configured?

**Comment by philippedurocher** [comment]
Good question. I'm using the bundle from tvaddons-dot-ag/tvmc-cordcutter. The addon updated itself when I completed the installation so I could use the authorization PIN code from Trakt. Apart from that, I cannot tell you if it's « the official » addon.

**Comment by tknorris** [comment]
It sounds like you do not. Salts depends on it for scrobbling and syncing.
Install it from system, addons, get addons, all addons, programs, trakt.

**Comment by philippedurocher** [comment]
Like I said in my OP, if I right click and use « Mark as watched » from within SALTS, it is registering as Watched on Trakt.tv. So my guess is I already have some kind of trakt addon installed. Since I'm at work right, I'll have to check back with you later. Thanks for your quick support.

**Comment by tknorris** [comment]
Nope. The right click mark as watched is a pure salts function.

**Comment by philippedurocher** [comment]
Everything is working now! I installed Trakt addon and now everything is ok. Thank you for your quick support.
