### ISSUE TITLE
When I start an episode from My Next Episodes I dont get the same results as when I start from Search

### ISSUE THREAD

**Issue by philippedurocher** [tknorris/salts#91]
I've been watching Naruto Shippuden from My Next Episode since about 2 weeks and I always got japanese version with english ST. Now when I try to stream any episodes, I always get sources for english version only. But when I use Search, the stream I find are in japanese with english ST. Did something change in the plugin? I don't remember changing anything in SALTS.

**Comment by tknorris** [comment]
Nope, thing has changed like this in SALTS. It's probably one of the scraper sites that changed something.

**Comment by philippedurocher** [comment]
Ok so do you know how I can get My Nex Episodes to scrape the same way the Search results does for the same episode? What should I look for?

**Comment by tknorris** [comment]
There's no difference in the logic between search results scraping and My Next Episodes. They both use the exact same logic (and code) to determine the correct scraper pages and sources. You might want to take a look at the Related Urls for the show and episodes and see if some of them are wrong. Read the 2nd post in this thread to understand how Related Url works: http://forums.tvaddons.ag/threads/26867-Stream-All-The-Sources-%28aka-SALTS%29-Beta-Test-Thread?p=228476&viewfull=1#post228476

**Comment by philippedurocher** [comment]
I'm not sure I fully understand. I've added the show for one of the source and now I can see it and can use it in My Next Episode. But still don't understand why it was already there in Search result but not in My Next Episode.

**Comment by tknorris** [comment]
There's no way for me to say without seeing it. I get the feeling there's something you think works one way, but actually works another...

**Comment by philippedurocher** [comment]
I can try to revert the changes I did and post some screenshot, but tomorrow, must go to sleep now. Thanks again for your help.
