### ISSUE TITLE
Duplicate TV Show folders with "(year)" being created

### ISSUE THREAD

**Issue by monisriz** [tknorris/salts#95]
At some point last week SALTS addon updated itself. Suddenly the new shows (Quantico e.g.) that I added to SALTS through trakt stopped getting added into the library. Upon further inspection of the salts addon folder I noticed that all the previous TV show folders were without the year (yyyy) at the end but now all of them were duplicated and had year at the end. Since the older shows had two copies the episodes, Kodi library still managed to scrap the older folders without the year. However, any new show that I added would only create one folder with the (yyyy) at the end and thus would not get scanned into the kodi library.

I tested this by manually removing the year from some folder names which weren't getting scanned and suddenly all seemed fine.

I am using Helix 14.2.

**Comment by tknorris** [comment]
You have two choices:
1) Update to Isengard. The Isengard TVDB scraper now allows a year on the TV Show folder
2) Stay on Helix and manually match each TV Show manually by selecting the TV Show folder in Kodi and hitting "I" and then picking  the correct show.

This is discussed in this issue: https://github.com/tknorris/salts/issues/94

**Comment by monisriz** [comment]
Thank you. Isengard fixed it. Appreciate your help and congratulate you on an amazing add-on!
