### ISSUE TITLE
no watch list

### ISSUE THREAD

**Issue by henry73** [tknorris/salts#96]
I have SALTS on 2 comps, but watchlist is not available on my laptop.  I would like to add it, but have been unable to do so.  Help?

**Comment by tknorris** [comment]
What do you mean it's unavailable? Unavailable where? If you mean in the tv show/movies menu, did you authorize SALTS to your trakt account? If not, you need to. Posting a screenshot might help.

**Comment by henry73** [comment]
thanks, I will check verification of trakt

**Comment by henry73** [comment]
WELL,MY MISTAKE TRAKT NOT AUTHORIZED, BUT IS NOW.  MANY THANKS
